<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    protected $guarded = [];

    function images(){
        return $this->hasMany(NewsImages::class,'fk_news');
    }
    function getRouteKeyName(){
        return 'url_title';
    }

    function __call($method, $parameters)
    {
        switch ($method){
            case 'createdY':
                return $this->created_at->format('Y');
                break;
            case 'createdM':
                return $this->created_at->format('m');
                break;
            case 'createdD':
                return $this->created_at->format('d');
                break;

        }
        return parent::__call($method, $parameters); // TODO: Change the autogenerated stub
    }
}
